config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'books/mybooks'
  get 'albums/myalbums'
  get 'albums/:id/booksrelated' => 'albums#booksrelated', as: 'albums_booksrelated'
  get 'albums/:id/addbooks' => 'albums#addbooks', as: 'albums_addbooks'
  get 'albums/:id/addbooktoalbum' => 'albums#addbooktoalbum', as: 'albums_addbooks_toalbum'
  get 'albums/:id/deletebook' => 'albums#deletebook', as: 'albums_deletebook'

  get 'books/:id/albumsrelated' => 'books#albumsrelated', as: 'books_albumsrelated'
  get 'books/:id/addalbums' => 'books#addalbums', as: 'books_addalbums'
  get 'books/:id/addalbumtobook' => 'books#addalbumtobook', as: 'books_addalbums_tobook'
  get 'books/:id/deletealbum' => 'books#deletealbum', as: 'books_deletealbum'
  get 'show_user/turnintoadmin' => 'show_user#turnintoadmin', as: 'turn_into_admin'

  resources :show_user
  resources :albums
  resources :books
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  has_attached_file :cover, :styles => { :large => "450x450", :medium => "300x300>", :thumb => "150x150>" }, :default_url => "/images/:style/none.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  has_and_belongs_to_many :books
  validates :title, :artist, presence: true, allow_blank: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_attached_file :cover, :styles => { :large => "500x762", :medium => "300x457>", :thumb => "100x152>" }, :default_url => "/images/:style/none.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  has_and_belongs_to_many :albums
  validates :title, :author, presence: true, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, :styles => { :large => "1000x1000", :medium => "400x400>", :thumb => "150x150>" }, :default_url => ""
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :albums
  has_many :books
  validates_uniqueness_of :user_name
  validates :first_name, :last_name, :user_name, presence: true, allow_blank: false
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy, :booksrelated, :addbooks, :addbooktoalbum, :deletebook]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  def myalbums
    @albums = current_user.albums
  end

  def booksrelated
  end

  def addbooktoalbum
      @album.books << Book.find(params[:bookid]) unless @album.books.include?(Book.find(params[:bookid]))
      redirect_to albums_addbooks_path(@album)

  end

  def deletebook
     @album.books.delete(Book.find(params[:bookid]))
     redirect_to albums_booksrelated_path(@album)
  end

  def addbooks
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = current_user.albums.build
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.build(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :artist, :genre, :year, :cover)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :albumsrelated, :addalbums, :addalbumtobook, :deletealbum]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  def mybooks
    @books = current_user.books
  end

  def albumsrelated
  end

  def addalbumtobook
    @book.albums << Album.find(params[:albumid]) unless @book.albums.include?(Album.find(params[:albumid]))
    redirect_to books_addalbums_path(@book)
  end

  def deletealbum
    @book.albums.delete(Album.find(params[:albumid]))
    redirect_to books_albumsrelated_path(@book)
  end

  def addalbums
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :genre, :year, :cover)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:avatar, :first_name, :last_name, :user_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:avatar, :first_name, :last_name, :user_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/show_user_controller.rb
class ShowUserController < ApplicationController

  def turnintoadmin
    current_user.update_attribute :admin, true
    redirect_to show_user_index_path
  end

  def index
     @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @home = true
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/show_user_helper.rb
module ShowUserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, multipart: true, local:true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", id:"exampleInputEmail1", :placeholder => "Title" %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, class: "form-control", id:"exampleInputEmail1", :placeholder => "Artist" %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "form-control", id:"exampleInputEmail1", :placeholder => "Genre" %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control", id:"exampleInputEmail1", :placeholder => "Year" %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-info" %>
  </div>

<% end %>

app/views/albums/addbooks.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <h1>Add Books to Album</h1>

  <p>
    <strong>Title:</strong>
    <%= @album.title %>
  </p>

  <p>
    <strong>Cover:</strong>
    <%= image_tag @album.cover.url(:medium) %>
  </p>

  <table class="table table-hover">
    <thead style="background-color: white; color:#1d5a67">
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Genre</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% Book.all.each do |book| %>
        <tr>
          <td><%= image_tag book.cover.url(:thumb) %></td>
          <td><%= book.title %></td>
          <td><%= book.genre %></td>
          <td><%= link_to 'Details', book, class: "btn btn-info", style: "color: white" %></td>
          <td><%= link_to 'Add', albums_addbooks_toalbum_path(bookid: book.id), data: { confirm: 'Do you confirm this adding?' }, class: "btn btn-info", style: "color: white" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Book', new_book_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/albums/booksrelated.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <h1>Books related to</h1>

  <p style="font-family:monospace; color:Black; font-size: 22px;">
    <%= @album.title %>
  </p>

  <p style="text-align:center;">
    <%= image_tag @album.cover.url(:medium) %>
  </p>

  <table class="table table-hover">
    <thead style="background-color: white; color:#1d5a67">
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @album.books.each do |book| %>
        <tr>
          <td><%= image_tag book.cover.url(:thumb) %></td>
          <td><%= book.title %></td>
          <td><%= link_to 'Details', book, class: "btn btn-info", style: "color: white" %></td>
          <%if current_user == @album.user || current_user.admin? %>
            <td><%= link_to 'Delete', albums_deletebook_path(bookid: book.id) , data: { confirm: 'Are you sure?' }, class: "btn btn-info", style: "color: white" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'Back', albums_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/albums/edit.html.erb
<div class = "form">
  <h1>Editing Album</h1>

  <%= render 'form', album: @album %>

  <%= link_to 'Back', @album, class: "btn btn-info", style: "color: white" %>
</div>

app/views/albums/index.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <h1>Albums</h1>

  <table class="table table-hover">
    <thead style="background-color: white; color:#1d5a67">
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Artist</th>
        <th>Genre</th>
        <th>Year</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @albums.each do |album| %>
        <tr>
          <td><%= image_tag album.cover.url(:thumb) %></td>
          <td><%= album.title %></td>
          <td><%= album.artist %></td>
          <td><%= album.genre %></td>
          <td><%= album.year %></td>
          <% if album.user.nil?%>
            <td>  </td>
          <% else %>
            <td><%= album.user.user_name%></td>
          <% end %>
          <td><%= link_to 'Details', album, class: "btn btn-info", style: "color: white" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Album', new_album_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/albums/myalbums.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <h1>My Albums</h1>

  <table class="table table-hover" >
    <thead style="background-color: white; color:#1d5a67">
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Artist</th>
        <th>Genre</th>
        <th>Year</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @albums.each do |album| %>
        <%if current_user == album.user%>
          <tr>
            <td><%= image_tag album.cover.url(:thumb) %></td>
            <td><%= album.title %></td>
            <td><%= album.artist %></td>
            <td><%= album.genre %></td>
            <td><%= album.year %></td>
            <td><%= link_to 'Details', album, class: "btn btn-info", style: "color: white" %></td>
            <td><%= link_to 'Add Books', albums_addbooks_path(album), class: "btn btn-info", style: "color: white" %></td>

          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Album', new_album_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/albums/new.html.erb
<div class = "form">
  <h1>New Album</h1>

  <%= render 'form', album: @album, class: "btn btn-info" %>

  <%= link_to 'Back', albums_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/albums/show.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <p style="color:Black; font-size: 16px;" >
    <strong style="color:#1d5a67" >Title:</strong>
    <%= @album.title %>
  </p>

  <p style="color:Black; font-size: 16px;" >
    <strong style="color:#1d5a67" >Artist:</strong>
    <%= @album.artist %>
  </p>

  <p style="color:Black; font-size: 16px;" >
    <strong style="color:#1d5a67" >Genre:</strong>
    <%= @album.genre %>
  </p>

  <p style="color:Black; font-size: 16px;" >
    <strong style="color:#1d5a67" >Year:</strong>
    <%= @album.year %>
  </p>

  <p style="color:Black; font-size: 16px;">
    <strong style="color:#1d5a67">Cover:</strong>
  </p>

  <p style="text-align:center;" >
    <%= image_tag @album.cover.url(:medium) %>
  </p>

  <%if current_user == @album.user  || current_user.admin?%>
    <%= link_to 'Edit', edit_album_path(@album), class: "btn btn-info", style: "color: white" %>
    <%= link_to 'Delete', @album, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info", style: "color: white" %>
  <% end %>
  <%= link_to 'Related Books', albums_booksrelated_path , class: "btn btn-info", style: "color: white" %>
  <%= link_to 'Back', albums_path, class: "btn btn-info", style: "color: white" %>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book, multipart: true, local:true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", id:"exampleInputEmail1", :placeholder => "Title" %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, class: "form-control", id:"exampleInputEmail1", :placeholder => "Author" %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre,  class: "form-control", id:"exampleInputEmail1", :placeholder => "Genre" %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control", id:"exampleInputEmail1", :placeholder => "Year" %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-info" %>
  </div>
<% end %>

app/views/books/addalbums.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <h1>Add Albums to Book</h1>

  <p>
    <%= @book.title %>
  </p>

  <p>
    <%= image_tag @book.cover.url(:thumb) %>
  </p>

  <table class="table table-hover">
    <thead style="background-color: white; color:#1d5a67">
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Artist</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% Album.all.each do |album| %>
        <tr>
          <td><%= image_tag album.cover.url(:thumb) %></td>
          <td><%= album.title %></td>
          <td><%= album.artist %></td>
          <td><%= link_to 'Details', album, class: "btn btn-info", style: "color: white" %></td>
          <td><%= link_to 'Add', books_addalbums_tobook_path(albumid: album.id), data: { confirm: 'Do You Confirm This Adding?' }, class: "btn btn-info", style: "color: white" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Album', new_album_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/books/albumsrelated.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <h1>Albums related to</h1>

  <p style="font-family:monospace; color:Black; font-size: 22px;">
    <%= @book.title %>
  </p>

  <p style="text-align:center;">
    <%= image_tag @book.cover.url(:medium) %>
  </p>

  <table class="table table-hover">
    <thead style="background-color: white; color:#1d5a67">
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Artist</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @book.albums.each do |album| %>
        <tr>
          <td><%= image_tag album.cover.url(:thumb) %></td>
          <td><%= album.title %></td>
          <td><%= album.artist %></td>
          <td><%= link_to 'Details', album, class: "btn btn-info", style: "color: white" %></td>
          <%if current_user == @book.user || current_user.admin? %>
            <td><%= link_to 'Delete', books_deletealbum_path(albumid: album.id) , data: { confirm: 'Are you sure?' }, class: "btn btn-info", style: "color: white" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Back', books_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/books/edit.html.erb
<div class = "form">
  <h1>Editing Book</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Back', @book, class: "btn btn-info", style: "color: white" %>
</div>

app/views/books/index.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <h1>Books</h1>

  <table class="table table-hover">
    <thead style="background-color: white; color:#1d5a67">
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Author</th>
        <th>Genre</th>
        <th>Year</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= image_tag book.cover.url(:thumb) %></td>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.genre %></td>
          <td><%= book.year %></td>
          <% if book.user.nil?%>
            <td>  </td>
          <% else %>
            <td><%= book.user.user_name%></td>
          <% end %>
          <td><%= link_to 'Details', book, class: "btn btn-info", style: "color: white" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Book', new_book_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/books/mybooks.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <h1>My Books</h1>

  <table class="table table-hover">
    <thead style="background-color: white; color:#1d5a67">
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Author</th>
        <th>Genre</th>
        <th>Year</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <% if current_user == book.user%>
          <tr>
            <td><%= image_tag book.cover.url(:thumb) %></td>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.genre %></td>
            <td><%= book.year %></td>
            <td><%= link_to 'Details', book, class: "btn btn-info", style: "color: white" %></td>
            <td><%= link_to 'Add Albums', books_addalbums_path(book), class: "btn btn-info", style: "color: white" %></td>
          </tr>
          <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Book', new_book_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/books/new.html.erb
<div class = "form">
  <h1>New Book</h1>

  <%= render 'form', book: @book, class: "btn btn-info" %>

  <%= link_to 'Back', books_path, class: "btn btn-info", style: "color: white" %>
</div>

app/views/books/show.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

  <p style="color:Black; font-size: 16px;">
    <strong style="color:#1d5a67">Title:</strong>
    <%= @book.title %>
  </p>


  <p style="color:Black; font-size: 16px;">
    <strong style="color:#1d5a67">Author:</strong>
    <%= @book.author %>
  </p>

  <p style="color:Black; font-size: 16px;">
    <strong style="color:#1d5a67">Genre:</strong>
    <%= @book.genre %>
  </p>

  <p style="color:Black; font-size: 16px;">
    <strong style="color:#1d5a67">Year:</strong>
    <%= @book.year %>
  </p>

  <p style="color:Black; font-size: 16px;">
    <strong style="color:#1d5a67">Cover:</strong>
  </p>

  <p   style="text-align:center;">
    <%= image_tag @book.cover.url(:medium) %>
  </p>

  <%if current_user == @book.user  || current_user.admin? %>
    <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-info", style: "color: white" %>
    <%= link_to 'Delete', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info", style: "color: white" %>
  <% end %>
  <%= link_to 'Related Albums', books_albumsrelated_path , class: "btn btn-info", style: "color: white" %>
  <%= link_to 'Back', books_path, class: "btn btn-info", style: "color: white" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlbumShelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="<%= @home? 'imgBg' : 'colorBg' %>">
    <nav class="navbar" style="background-color: #1d5a67;">
      <font href="#"><%= link_to 'AlbumShelf', welcome_index_path, style: "text-decoration: none; color: white; font-size: 25px; font-family: Ubuntu" %></font>
      <% if user_signed_in? %>
        <div class="round_image"><%= image_tag(current_user.avatar.url(:thumb)) %></div>
        <strong style="color:#B0E0E6"> Hello, <%= current_user.user_name %> </strong>
        <%= link_to 'Albums', albums_path, style: "text-decoration: none; color: white"%>
        <%= link_to 'Books', books_path, style: "text-decoration: none; color: white"%>
        <%= link_to 'My Albums', albums_myalbums_path, style: "text-decoration: none; color: white"%>
        <%= link_to 'My Books', books_mybooks_path, style: "text-decoration: none; color: white"%>
      <% end %>
      <% if user_signed_in? == false %>
        <%= link_to 'Log In', new_user_session_path, style: "text-decoration: none; color: white"%>
        <%= link_to 'Sign Up', new_user_registration_path, style: "text-decoration: none; color: white"%>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to 'Profile', show_user_index_path, style: "text-decoration: none; color: white"%>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, style: "text-decoration: none; color: white"%>
      <% end %>
    </nav>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/show_user/index.html.erb
<div class = "form">
  <p id="notice"><%= notice %></p>

    <%if current_user.admin?%>
        <strong style="color:#1d5a67; font-size: 35px" >Admin User</strong>
    <%end%>

  <p>

    <%= image_tag (current_user.avatar.url(:thumb)) %>
  </p>

  <p style="color:Black; font-size: 16px;" >
    <strong style="color:#1d5a67" >First Name:</strong>
    <%= @user.first_name %>
  </p>

  <p style="color:Black; font-size: 16px;" >
    <strong style="color:#1d5a67" >Last Name:</strong>
    <%= @user.last_name %>
  </p>

  <p style="color:Black; font-size: 16px;" >
    <strong style="color:#1d5a67" >User Name:</strong>
    <%= @user.user_name %>
  </p>

  <p style="color:Black; font-size: 16px;" >
    <strong style="color:#1d5a67" >Email:</strong>
    <%= @user.email %>
  </p>

  <%= link_to 'Edit', edit_user_registration_path(@user), class: "btn btn-info", style: "color: white" %>
</div>

app/views/welcome/index.html.erb
<div class = "home_page" align="center" >


</div>